title: MMC20 Application Lateral Movement
description: Detection Engineering, Threat Hunting and Security Research Blog

remote_theme: "mmistakes/minimal-mistakes"

minimal_mistakes_skin: "dark"

plugins:
  - jekyll-feed
  - jekyll-include-cache

show_downloads: false

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/
