theme: jekyll-theme-minimal

title: MMC20 Application Lateral Movement
description: Detection Engineering, Threat Hunting and Security Research Blog

show_downloads: false

github:
  is_project_page: false
