title: MMC20 Application Lateral Movement
description: Detection Engineering, Threat Hunting and Security Research Blog

remote_theme: "mmistakes/minimal-mistakes"

minimal_mistakes_skin: "dark"

url: "https://mahdinikfarjam003.github.io"
baseurl: ""

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-paginate

permalink: /:categories/:year/:month/:day/:title/

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/

markdown: kramdown
highlighter: rouge
